import type { Logger } from '../logger';

/**
 * Represents a file to be generated by the init command
 */
export interface TemplateFile {
  name: string;
  contents: string;
}

/**
 * Represents a prompt answer collected during init
 */
export interface PromptAnswer {
  name: string;
  answer: string | boolean;
}

/**
 * Git configuration parsed from ~/.gitconfig
 */
export interface GitConfig {
  user: {
    name?: string;
    email?: string;
  };
}

/**
 * Options for the init command
 */
export interface InitOptions {
  cwd: string;
  path: string;
  silent?: boolean;
  debug?: boolean;
  logger: Logger;
}

/**
 * Context passed to file generation
 */
export interface InitContext {
  cwd: string;
  packagePath: string;
  packageFolder: string;
  gitConfig: GitConfig | null;
  logger: Logger;
}
